blog/urls.py
from django.urls import path
from .views import (post_detail,
                    PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    post_share)


app_name = 'blog'
urlpatterns = [
    # post views
    # path(r'^$', post_list, name='post_list'),
    path('', PostListView.as_view(), name='post_list'),
    path('<slug:post>/', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('post/create', PostCreateView.as_view(), name='post_create'),
    path('<slug>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<slug>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

templates/snippets/nav.html
<nav class="navbar navbar-custom navbar-light navbar-expand-md fixed-top">
    <div class="container">
        <!--navbar brand-->
        <a class="navbar-brand custom mr-4" href="{% url 'blog:post_list' %}">Programming Blog</a>
        <button type="button"
            class="navbar-toggler"
            data-toggle="collapse"
            data-target="#navbar"
            aria-expanded="false"
            aria-controls="bd-main-nav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!--navbar home about-->
        <div id="navbar" class="collapse navbar-collapse">
            <!--Navbar Left Side-->
            <div class="navbar-nav mr-auto">
                <a class="nav-link custom" href="{% url 'blog:post_list' %}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-link custom" href="{% url 'blog:post_create' %}">New Post</a>
                        <a class="nav-link custom" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-link custom" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-link custom" href="{% url 'login' %}">Login</a>
                        <a class="nav-link custom" href="{% url 'register' %}">Register</a>
                    {% endif %}
            </div>
        </div>

    </div>
</nav>