blog/urls.py
from django.urls import path
from .views import (post_detail,
                    PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    post_share)


app_name = 'blog'
urlpatterns = [
    # post views
    # path(r'^$', post_list, name='post_list'),
    path('', PostListView.as_view(), name='post_list'),
    path('<slug:post>/', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('post/create', PostCreateView.as_view(), name='post_create'),
    path('<slug>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<slug>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(
                PublishedManager,
                self).get_queryset().filter(status='draft')


class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICE,
                              default='draft')

    objects = models.Manager()          # default the manager
    published = PublishedManager()        # our custom manager

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        """
        form post - auto save slug
        """
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)



class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail


class PostListView(ListView):
    model = Post                        # queryset = Post.objects.all()
    context_object_name = 'posts'   # can remove - object_list default tmplates
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post)

    # Comment to blog post
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            # Create comment object but don't save to db yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the db
            new_comment.save()

    else:
        comment_form = CommentForm()

    return render(request, 'blog/post/detail.html', {
                                                'post': post,
                                                'comments': comments,
                                                'comment_form': comment_form
                                                    })


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post/create.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        """
        required author before to submit form
        """
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Update post by User
    """
    model = Post
    template_name = 'blog/post/create.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        """
        required author before to submit form
        """
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        """
        Test if the user is equal to author
        """
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        """
        Test if the user is equal to author
        """
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def post_share(request, post_id):
    # retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='draft')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                    cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                    post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

blog/templates/blog/post/create.html
{% extends "blog/blog.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{ block.super }} | Create
{% endblock title %}

{% block content %}
<br>
<br>
<br>
    <div class="content-section" style="width: 480px;">
	<h1>New Post</h1>
    <form method="POST"> {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info" type="submit">Post</button>
        </div>
    </form>
    </div>

{% endblock content %}

blog/templates/blog/post/detail.html
{% extends "blog/blog.html" %}

{% block title %}
    {{ block.super }} | Detail
{% endblock title %}

{% block content_blog %}
	<h1> {{ post.title }} </h1>
	<p class="date">
		Published {{ post.publish }} by {{ post.author }}

	</p>
	{{ post.body | linebreaks }}
    <p>
    <p>
        {% if post.author == user %}
            <a class="btn btn-info" href="{% url 'blog:post_update' post.slug %}">Update</a>
            <a class="btn btn-danger" href="{% url 'blog:post_delete' post.slug %}">Delete</a>
        {% endif %}
    </p>
    <a href="{% url 'blog:post_share' post.id %}">
        Share this post
    </a>
    </p>
    <hr><hr>
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment {{ total_comments | pluralize  }}
    </h2>
    {% endwith %}

    {% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name  }}
            {{ comment.created  }}
        </p>
        {{ comment.body | linebreaks  }}
    </div>
    {% empty %}
    <p> There are no comments yet </p>
    {% endfor %}

    {% if new_comment %}
    <h2> Your comment has been added</h2>
    {% else %}
    <h2> Add new comment </h2>
    <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input class="comment-button" type="submit" value="Add comment"></p>
    </form>
    {% endif %}
{% endblock content_blog %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/blog.html" %}

{% block title %}
    {{ block.super }} | Home
{% endblock title %}

{% block content_blog %}
	<h1>Blog </h1>
	{# <p> <a href="{% url 'blog:post_create' %}"> + New Post </a> </p> #}
	{% for post in posts  %}
		<h3>
			<a href="{{ post.get_absolute_url }}">
				{{ post.title }}
			</a>
		</h3>
		<p class="date">
			Published {{ post.publish }} by {{ post.author }}
		</p>
		{{ post.body|truncatewords:15|linebreaks }}
	{% endfor %}
	{% include "pagination.html" with page=page_obj %}
{% endblock content_blog %}

blog/templates/blog/post/share.html
{% extends "blog/blog.html" %}

{% block title %}
    {{ block.super }} | Share
{% endblock %}
{% block content_blog %}
    {% if sent %}
        <h1> E-mail Succesfully sent </h1>
        <p>
            "{{ post.title }}" was succesfully sent send to {{ cd.to }}
        </p>

    {% else %}
        <h1> Share "{{ post.title }}" by email </h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock content_blog %}